version: "3.9"
services:
  database:
    container_name: postgres-db
    image: "postgres:12"
    env_file: .env
    environment:
      PGDATA: ${POSTGRES_PGDATA}
    restart: on-failure
  backend:
    container_name: "kpp-back"
    build: 
      context: ./backend
    ports:
      - "4000:3000"
    env_file: .env
    depends_on:
      - database
    restart: on-failure
  frontend:
    container_name: "kpp-front"
    build:
      context: ./frontend
    ports:
      - "8081:80"
    restart: on-failure
