FROM node:16-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY ./src ./src
COPY ./nest-cli.json ./
COPY ./tsconfig.json ./
COPY ./tsconfig.build.json ./
COPY ./ecosystem.config.js ./

RUN npm run build
#######################

FROM node:16-alpine AS prod
WORKDIR /app

ARG JWT_SECRET=D%8+jQ$e>/G!XR3Su.,8
ENV JWT_SECRET=$JWT_SECRET

ARG POSTGRES_PORT=5432
ENV POSTGRES_PORT=$POSTGRES_PORT

ARG POSTGRES_PASSWORD=student
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

ARG POSTGRES_DB=kupipodariday
ENV POSTGRES_DB=$POSTGRES_DB

ARG POSTGRES_USER=student
ENV POSTGRES_USER=$POSTGRES_USER

ARG POSTGRES_HOST=localhost
ENV POSTGRES_HOST=$POSTGRES_HOST

ARG POSTGRES_PGDATA
ENV POSTGRES_PGDATA=$POSTGRES_PGDATA

COPY --from=builder /app/package*.json ./

RUN npm i --omit-dev

RUN npm i -g pm2

COPY --from=builder /app/dist ./dist/
COPY --from=builder ./app/ecosystem.config.js ./

EXPOSE 3000

CMD ["pm2-runtime", "ecosystem.config.js"]
