version: "3.8"
services:
  kpp-back:
    build: 
      context: . 
    image: "kpp-back"
    ports:
      - "4000:3000"
    env_file: .env
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    image: "postgres:12"
    env_file: .env
    environment:
      PGDATA: ${POSTGRES_PGDATA}
  frontend:
    build:
      context: ./../frontend
    image: "kpp-front"
    ports:
      - "8081:80"
