version: "1.0"
services:
  kpp-back:
    build: 
      context: . 
    image: "kpp-back"
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - postgres-db
  postgres-db:
    container_name: postgres-db
    image: "postgres:12"
    env_file: .env
    environment:
      PGDATA: ${POSTGRES_PGDATA}
